(function(g){var window=this;'use strict';var yWa=function(a,b){a.Ma("onAutonavCoundownStarted",b)},m3=function(a,b,c){g.N(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Re(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.sD&&(b.lengthText?(e=b.lengthText||null,f=b.Nq||null):b.lengthSeconds&&(e=g.hJ(b.lengthSeconds),f=g.hJ(b.lengthSeconds,!0)));var k=!!d;d=k&&"RD"===g.oD(d).type;var l=b instanceof g.sD?b.isLivePlayback:null,m=b instanceof g.sD?b.isUpcoming:null;c={title:b.title,author:b.author,author_and_views:b.shortViewCount?b.author+" \u2022 "+b.shortViewCount:b.author,aria_label:b.ariaLabel||g.MF("Watch $TITLE",{TITLE:b.title}),duration:e,
timestamp:f,url:b.jl(),is_live:l,is_upcoming:m,is_list:k,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:b.shortViewCount?b.shortViewCount+" \u2022 "+b.publishedTimeText:b.publishedTimeText,autoplayAlternativeHeader:b.Hn};b instanceof g.rD&&(c.playlist_length=b.playlistLength);a.update(c)},n3=function(a){var b=a.V(),c=b.j;
g.W.call(this,{G:"a",L:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:c?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",Fa:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Fa:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Fa:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",
Fa:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"},{G:"div",L:"ytp-autonav-list-overlay",U:[{G:"div",L:"ytp-autonav-mix-text",oa:"Mix"},{G:"div",L:"ytp-autonav-mix-icon"}]}]},{G:"div",Fa:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],oa:"{{title}}"},{G:"div",Fa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],oa:"{{author}}"},{G:"div",Fa:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],oa:"{{views_and_publish_time}}"}]});this.I=a;this.suggestion=
null;this.j=c;this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress)},p3=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{G:"div",L:"ytp-autonav-endscreen-countdown-container"});var c=this;this.J=b;this.D=void 0;this.u=0;b=a.V();var d=b.j;this.I=a;this.suggestion=null;this.onVideoDataChange("newdata",this.I.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({G:"div",L:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},U:[{G:"div",
L:"ytp-autonav-endscreen-upnext-header"},{G:"div",L:"ytp-autonav-endscreen-upnext-alternative-header",oa:"{{autoplayAlternativeHeader}}"},{G:"a",L:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:d?b.K:""},U:[{G:"div",L:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},U:[{G:"div",W:{"aria-label":"{{timestamp}}"},Fa:["ytp-autonav-timestamp"],oa:"{{duration}}"},{G:"div",Fa:["ytp-autonav-live-stamp"],oa:"Live"},{G:"div",Fa:["ytp-autonav-upcoming-stamp"],oa:"Upcoming"}]},
{G:"div",L:"ytp-autonav-endscreen-video-info",U:[{G:"div",L:"ytp-autonav-endscreen-premium-badge"},{G:"div",L:"ytp-autonav-endscreen-upnext-title",oa:"{{title}}"},{G:"div",L:"ytp-autonav-endscreen-upnext-author",oa:"{{author}}"},{G:"div",L:"ytp-autonav-view-and-date",oa:"{{views_and_publish_time}}"},{G:"div",L:"ytp-autonav-author-and-view",oa:"{{author_and_views}}"}]}]}]});g.H(this,this.j);this.j.Ba(this.element);d||this.T(this.j.Ca("ytp-autonav-endscreen-link-container"),"click",this.hK);this.I.Ab(this.element,
this,115127);this.I.Ab(this.j.Ca("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({G:"div",L:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.B=new g.W({G:"div",L:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ba(this.element);this.cancelButton=new g.W({G:"button",Fa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button"],W:{"aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);
this.cancelButton.Ba(this.B.element);this.cancelButton.Oa("click",this.QS,this);this.I.Ab(this.cancelButton.element,this,115129);this.playButton=new g.W({G:"a",Fa:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button"],W:{href:"{{url}}",role:"button","aria-label":"Play next video"},oa:"Play Now"});g.H(this,this.playButton);this.playButton.Ba(this.B.element);this.playButton.Oa("click",this.hK,this);this.I.Ab(this.playButton.element,this,115130);this.C=new g.L(function(){o3(c)},
500);
g.H(this,this.C);this.gK();this.T(a,"autonavvisibility",this.gK)},s3=function(a){var b=a.I.Lj(!0,a.I.isFullscreen());
g.N(a.element,"ytp-autonav-endscreen-small-mode",a.Df(b));g.N(a.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.pC);g.N(a.I.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.I.Ae());g.N(a.I.getRootNode(),"countdown-running",a.Rh());g.N(a.element,"ytp-player-content",a.I.Ae());g.Nm(a.overlay.element,{width:b.width+"px"});if(!a.Rh()){a.I.Ae()?q3(a,Math.round(r3(a)/1E3)):q3(a);b=!!a.suggestion&&!!a.suggestion.Hn;var c=a.I.Ae()||!b;g.N(a.element,"ytp-autonav-endscreen-upnext-alternative-header-only",
!c&&b);g.N(a.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.iI(a.B,a.I.Ae())}},o3=function(a){var b=r3(a),c=Math,d=c.min;
var e=a.u?Date.now()-a.u:0;c=d.call(c,e,b);q3(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Rh()?a.select(!0):a.Rh()&&a.C.start()},r3=function(a){var b=a.I.mq();
return 0<=b?b:g.tB(a.I.V().experiments,"autoplay_time")||1E4},q3=function(a,b){b=void 0===b?-1:b;
a=a.j.Ca("ytp-autonav-endscreen-upnext-header");g.ii(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.hi("Up next in $SECONDS".slice(0,d)));var e=g.gi("span");g.Dp(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.ni(e,b);a.appendChild(e);a.appendChild(g.hi("Up next in $SECONDS".slice(d+c.length)));return}}g.ni(a,"Up next")},t3=function(a,b){g.W.call(this,{G:"div",
Fa:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},u3=function(a){g.W.call(this,{G:"div",
Fa:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},U:[{G:"div",L:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-upnext-top",U:[{G:"span",L:"ytp-upnext-header",oa:"Up Next"},{G:"span",L:"ytp-upnext-title",oa:"{{title}}"},{G:"span",L:"ytp-upnext-author",oa:"{{author}}"}]},{G:"a",L:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Play next video"},U:[{G:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
U:[{G:"circle",L:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",L:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",L:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",L:"ytp-upnext-bottom",U:[{G:"span",L:"ytp-upnext-cancel"},{G:"span",L:"ytp-upnext-paused",
oa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.D=this.Ca("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.L(this.Uz,5E3,this);this.u=0;var b=this.Ca("ytp-upnext-cancel");this.cancelButton=new g.W({G:"button",Fa:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Cancel autoplay"},oa:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Oa("click",this.RS,this);this.cancelButton.Ba(b);this.cancelButton&&this.api.Ab(this.cancelButton.element,
this,115129);g.H(this,this.C);this.api.Ab(this.element,this,18788);b=this.Ca("ytp-upnext-autoplay-icon");this.T(b,"click",this.SS);this.api.Ab(b,this,115130);this.iK();this.T(a,"autonavvisibility",this.iK);this.T(a,"mdxnowautoplaying",this.CX);this.T(a,"mdxautoplaycanceled",this.DX);g.N(this.element,"ytp-upnext-mobile",this.api.V().isMobile)},zWa=function(a,b){return b?b:0<=a.api.mq()?a.api.mq():g.tB(a.api.V().experiments,"autoplay_time")||1E4},v3=function(a,b){b=zWa(a,b);
var c=Math,d=c.min;var e=(0,g.R)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Rh()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Rh()&&a.j.start()},w3=function(a){t3.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({G:"div",L:"ytp-suggestion-panel",U:[{G:"div",Fa:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],oa:"More videos"}]});this.K=new g.W({G:"div",L:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.J=!1;this.u=new p3(this.player);g.H(this,this.u);this.u.Ba(this.element);a.getVideoData().Wb?this.j=this.u:(this.j=new u3(a),g.ZK(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.W({G:"div",
L:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ba(this.element);this.C=new g.jA(this);g.H(this,this.C);g.H(this,this.table);this.table.Ba(this.element);this.table.show();g.H(this,this.K);this.K.Ba(this.table.element);this.hide()},x3=function(a){var b=a.Ae();
b!==a.D&&(a.D=b,a.player.ea("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},y3=function(a){t3.call(this,a,"subscribecard-endscreen");
this.j=new g.W({G:"div",L:"ytp-subscribe-card",U:[{G:"img",L:"ytp-author-image",W:{src:"{{profilePicture}}"}},{G:"div",L:"ytp-subscribe-card-right",U:[{G:"div",L:"ytp-author-name",oa:"{{author}}"},{G:"div",L:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.Ba(this.element);var b=a.getVideoData();this.subscribeButton=new g.qM("Subscribe",null,"Unsubscribe",null,!0,!1,b.rj,b.subscribed,"trailer-endscreen",null,null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ba(this.j.Ca("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Ja);this.Ja();this.hide()},z3=function(a){var b=a.V(),c=g.nA||g.pC?{style:"will-change: opacity"}:void 0,d=b.j,e=["ytp-videowall-still"];
b.isMobile&&e.push("ytp-videowall-show-text");g.W.call(this,{G:"a",Fa:e,W:{href:"{{url}}",target:d?b.K:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},U:[{G:"div",L:"ytp-videowall-still-image",W:{style:"{{background}}"}},{G:"span",L:"ytp-videowall-still-info",U:[{G:"span",L:"ytp-videowall-still-info-bg",U:[{G:"span",L:"ytp-videowall-still-info-content",W:c,U:[{G:"span",L:"ytp-videowall-still-info-title",oa:"{{title}}"},{G:"span",
L:"ytp-videowall-still-info-author",oa:"{{author_and_views}}"},{G:"span",L:"ytp-videowall-still-info-live",oa:"Live"},{G:"span",L:"ytp-videowall-still-info-duration",oa:"{{duration}}"}]}]}]},{G:"span",Fa:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],U:[{G:"span",L:"ytp-videowall-still-listlabel-icon"},"Playlist",{G:"span",L:"ytp-videowall-still-listlabel-length",U:[" (",{G:"span",oa:"{{playlist_length}}"},")"]}]},{G:"span",Fa:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],
U:[{G:"span",L:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{G:"span",L:"ytp-videowall-still-listlabel-length",oa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.jA(this);g.H(this,this.j);this.Oa("click",this.onClick);this.Oa("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.dh(this.element,this);this.onVideoDataChange()},A3=function(a){t3.call(this,a,"videowall-endscreen");
var b=this;this.I=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.K=!1;this.N=null;this.u=new g.jA(this);g.H(this,this.u);this.J=new g.L(function(){g.M(b.element,"ytp-show-tiles")},0);
g.H(this,this.J);var c=new g.W({G:"button",Fa:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Previous"},U:[g.nI()]});g.H(this,c);c.Ba(this.element);c.Oa("click",this.XS,this);this.table=new g.fI({G:"div",L:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ba(this.element);c=new g.W({G:"button",Fa:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Next"},U:[g.oI()]});g.H(this,c);c.Ba(this.element);c.Oa("click",this.WS,this);a.getVideoData().Wb?this.j=new p3(a,!0):this.j=new u3(a);
g.H(this,this.j);g.ZK(this.player,this.j.element,4);this.hide()},B3=function(a){return g.$K(a.player)&&a.ew()&&!a.C},C3=function(a){var b=a.Ae();
b!==a.K&&(a.K=b,a.player.ea("autonavvisibility"))},D3=function(a){g.lL.call(this,a);
var b=this;this.endScreen=null;this.j=this.u=this.B=!1;this.listeners=new g.jA(this);g.H(this,this.listeners);this.env=a.V();AWa(a)?(this.B=!0,BWa(this),this.j?this.endScreen=new w3(a):this.endScreen=new A3(this.player)):this.env.Qd?this.endScreen=new y3(this.player):this.endScreen=new t3(this.player);g.H(this,this.endScreen);g.ZK(this.player,this.endScreen.element,4);CWa(this);this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.Lw("endscreen"),function(c){b.onCueRangeEnter(c)});
this.listeners.T(a,g.Mw("endscreen"),function(c){b.onCueRangeExit(c)})},BWa=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Sh&&a.u===b.Wb)return!1;a.j=b.Sh;a.u=b.Wb;return!0},AWa=function(a){a=a.V();
return!a.C&&a.Kb&&!a.Qd},CWa=function(a){a.player.jf("endscreen");
var b=a.player.getVideoData();b=new g.Jw(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.Jw(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Rd([b,c])};
g.SK.prototype.mq=g.da(4,function(){return this.app.mq()});
g.PU.prototype.mq=g.da(3,function(){return this.getVideoData().rP});g.v(n3,g.W);n3.prototype.select=function(){(this.I.rk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Dw||void 0)||this.I.S("web_player_endscreen_double_log_fix_killswitch"))&&this.I.wb(this.element)};
n3.prototype.onClick=function(a){g.KL(a,this.I,this.j,this.suggestion.sessionData||void 0)&&this.select()};
n3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.xu(a)||(this.select(),g.wu(a))}};g.v(p3,g.W);g.h=p3.prototype;g.h.wz=function(a){this.suggestion!==a&&(this.suggestion=a,m3(this.j,a),this.playButton.Ka("url",this.suggestion.jl()),s3(this))};
g.h.Rh=function(){return 0<this.u};
g.h.Hu=function(){this.Rh()||(this.u=Date.now(),o3(this),yWa(this.I,r3(this)),g.N(this.I.getRootNode(),"countdown-running",this.Rh()))};
g.h.Yq=function(){this.hn();o3(this);var a=this.j.Ca("ytp-autonav-endscreen-upnext-header");a&&g.ni(a,"Up next")};
g.h.hn=function(){this.Rh()&&(this.C.stop(),this.u=0)};
g.h.select=function(a){this.I.nextVideo(!1,void 0===a?!1:a);this.hn()};
g.h.hK=function(a){g.KL(a,this.I)&&(a.currentTarget===this.playButton.element?this.I.wb(this.playButton.element):a.currentTarget===this.j.Ca("ytp-autonav-endscreen-link-container")&&(a=this.j.Ca("ytp-autonav-endscreen-link-container"),this.I.Za(a,!0),this.I.wb(a)),this.select())};
g.h.QS=function(){this.I.wb(this.cancelButton.element);g.UK(this.I,!0);this.D&&this.I.Ma("innertubeCommand",this.D)};
g.h.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.Y_)?void 0:c.command};
g.h.gK=function(){var a=this.I.Ae();this.J&&this.tb!==a&&g.iI(this,a);s3(this);this.I.Za(this.element,a);this.I.Za(this.cancelButton.element,a);this.I.Za(this.j.Ca("ytp-autonav-endscreen-link-container"),a);this.I.Za(this.playButton.element,a)};
g.h.Df=function(a){return 400>a.width||459>a.height};g.v(t3,g.W);g.h=t3.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.ew=function(){return!1};
g.h.Ae=function(){return!1};
g.h.pN=function(){return!1};g.v(u3,g.W);g.h=u3.prototype;g.h.Uz=function(){this.notification&&(this.C.stop(),this.vc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.h.wz=function(a){this.suggestion=a;m3(this,a,"hqdefault.jpg")};
g.h.iK=function(){g.iI(this,this.api.Ae());this.api.Za(this.element,this.api.Ae());this.api.Za(this.Ca("ytp-upnext-autoplay-icon"),this.api.Ae());this.cancelButton&&this.api.Za(this.cancelButton.element,this.api.Ae())};
g.h.LX=function(){window.focus();this.Uz()};
g.h.Hu=function(a){var b=this;this.Rh()||(g.Lu("a11y-announce","Up Next "+this.suggestion.title),this.u=(0,g.R)(),this.j=new g.L(function(){v3(b,a)},25),v3(this,a),yWa(this.api,zWa(this,a)));
g.Gp(this.element,"ytp-upnext-autoplay-paused")};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.Rh=function(){return!!this.j};
g.h.Yq=function(){this.hn();this.u=(0,g.R)();v3(this);g.M(this.element,"ytp-upnext-autoplay-paused")};
g.h.hn=function(){this.Rh()&&(this.j.dispose(),this.j=null)};
g.h.select=function(a){a=void 0===a?!1:a;if(this.api.V().S("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.Uz(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Re()}),this.B=this.T(this.notification,"click",this.LX),this.C.start())}this.hn();this.api.nextVideo(!1,a)};
g.h.SS=function(a){!g.mi(this.cancelButton.element,g.ru(a))&&g.KL(a,this.api)&&(this.api.Ae()&&this.api.wb(this.Ca("ytp-upnext-autoplay-icon")),this.select())};
g.h.RS=function(){this.api.Ae()&&this.cancelButton&&this.api.wb(this.cancelButton.element);g.UK(this.api,!0)};
g.h.CX=function(a){this.api.getPresentingPlayerType();this.show();this.Hu(a)};
g.h.DX=function(){this.api.getPresentingPlayerType();this.hn();this.hide()};
g.h.qa=function(){this.hn();this.Uz();g.W.prototype.qa.call(this)};g.v(w3,t3);g.h=w3.prototype;g.h.create=function(){t3.prototype.create.call(this);this.C.T(this.player,"appresize",this.Gv);this.C.T(this.player,"onVideoAreaChange",this.Gv);this.C.T(this.player,"videodatachange",this.onVideoDataChange);this.C.T(this.player,"autonavchange",this.jK);this.C.T(this.player,"autonavcancel",this.US);this.onVideoDataChange()};
g.h.show=function(){t3.prototype.show.call(this);(this.J||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.UK(this.player,!1);g.$K(this.player)&&this.ew()&&!this.B?(x3(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Hu():3===this.videoData.autonavState&&this.j.Yq()):(g.UK(this.player,!0),x3(this));this.Gv()};
g.h.hide=function(){t3.prototype.hide.call(this);this.j.Yq();x3(this)};
g.h.Gv=function(){var a=this.player.Lj(!0,this.player.isFullscreen());x3(this);s3(this.u);g.N(this.element,"ytp-autonav-cancelled-small-mode",this.Df(a));g.N(this.element,"ytp-autonav-cancelled-tiny-mode",this.ZA(a));g.N(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Nm(this.overlay.element,{width:a.width+"px"});if(!this.D){a=g.r(this.videos.entries());for(var b=a.next();!b.done;b=a.next()){var c=g.r(b.value);b=c.next().value;c=c.next().value;g.N(c.element,
"ytp-suggestion-card-with-margin",1===b%2)}}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length){this.j.wz(a[0]);this.j!==this.u&&this.u.wz(a[0]);for(var b=0;b<DWa.length;++b){var c=DWa[b];if(a&&a[c]){this.videos[b]=new n3(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,m3(d,c));g.H(this,this.videos[b]);this.videos[b].Ba(this.K.element)}}}this.Gv()}};
g.h.jK=function(a){1===a?(this.J=!1,this.B=this.videoData.clientPlaybackNonce,this.j.hn(),this.tb&&this.Gv()):(this.J=!0,this.Ae()&&(2===a?this.j.Hu():3===a&&this.j.Yq()))};
g.h.US=function(a){a?this.jK(1):(this.B=null,this.J=!1)};
g.h.ew=function(){return 1!==this.videoData.autonavState};
g.h.Df=function(a){return(910>a.width||459>a.height)&&!this.ZA(a)&&!(400>=a.width||360>=a.height)};
g.h.ZA=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.h.Ae=function(){return this.tb&&g.$K(this.player)&&this.ew()&&!this.B};
var DWa=[1,3,2,4];g.v(y3,t3);y3.prototype.Ja=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.rj;var b=this.subscribeButton;a.subscribed?b.u():b.B()};g.v(z3,g.W);z3.prototype.select=function(){(this.api.rk(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Dw||void 0)||this.api.S("web_player_endscreen_double_log_fix_killswitch"))&&this.api.wb(this.element)};
z3.prototype.onClick=function(a){g.KL(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
z3.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.xu(a)||(this.select(),g.wu(a))}};
z3.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.j};g.v(A3,t3);g.h=A3.prototype;g.h.create=function(){t3.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Rl();this.u.T(this.player,"appresize",this.Rl);this.u.T(this.player,"onVideoAreaChange",this.Rl);this.u.T(this.player,"videodatachange",this.onVideoDataChange);this.u.T(this.player,"autonavchange",this.BD);this.u.T(this.player,"autonavcancel",this.VS);a=this.videoData.autonavState;a!==this.N&&this.BD(a);this.u.T(this.element,"transitionend",this.aZ)};
g.h.destroy=function(){g.iv(this.u);g.rf(this.stills);this.stills=[];t3.prototype.destroy.call(this);g.Gp(this.element,"ytp-show-tiles");this.J.stop();this.N=this.videoData.autonavState};
g.h.ew=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){t3.prototype.show.call(this);g.Gp(this.element,"ytp-show-tiles");this.player.V().isMobile?g.zp(this.J):this.J.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.UK(this.player,!1);B3(this)?(C3(this),2===this.videoData.autonavState?this.player.V().S("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Hu():3===this.videoData.autonavState&&this.j.Yq()):(g.UK(this.player,!0),C3(this))};
g.h.hide=function(){t3.prototype.hide.call(this);this.j.Yq();C3(this)};
g.h.aZ=function(a){g.ru(a)===this.element&&this.Rl()};
g.h.Rl=function(){if(this.videoData&&this.videoData.suggestions&&this.videoData.suggestions.length){g.M(this.element,"ytp-endscreen-paginate");var a=this.I.Lj(!0,this.I.isFullscreen()),b=g.PK(this.I);b&&(b=b.bf()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.videoData.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,q=e/2,t=b<=f-2&&n>=q*m,w=e<=k-2&&n>=p*m;if((p+
1)/q*d/c>c/(p/(q+1)*d)&&w)n-=p*m,e+=2;else if(t)n-=q*m,b+=2;else if(w)n-=p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m=Math.floor(Math.min(a.width,m*c));n=Math.floor(Math.min(a.height,n*c));a=this.table.element;g.Xm(a,m,n);g.Nm(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});this.j.wz(this.videoData.suggestions[0]);this.j instanceof p3&&s3(this.j);g.N(this.element,"ytp-endscreen-takeover",B3(this));C3(this);m+=4;n+=4;for(f=
c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,p=0,d&&f>=b-2&&k>=e-2?p=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(p=2):p=2),q=g.xh(q+this.B,l),0!==p){t=this.stills[c];t||(t=new z3(this.player),this.stills[c]=t,a.appendChild(t.element));w=Math.floor(n*k/e);var x=Math.floor(m*f/b),y=Math.floor(n*(k+p)/e)-w-4,z=Math.floor(m*(f+p)/b)-x-4;g.Tm(t.element,x,w);g.Xm(t.element,z,y);g.Nm(t.element,"transitionDelay",(k+f)/20+"s");g.N(t.element,"ytp-videowall-still-mini",1===p);g.N(t.element,"ytp-videowall-still-large",
2<p);p=t;q=this.videoData.suggestions[q];p.suggestion!==q&&(p.suggestion=q,t=p.api.V(),w=g.Ep(p.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",m3(p,q,w),g.rC(t)&&(w=q.jl(),x={},t.ma&&g.mK(x,t.loaderUrl),w=g.yj(w,g.lK(x,"emb_rel_end")),p.Ka("url",w)),(q=(q=q.sessionData)&&q.itct)&&p.api.hk(p.element,q));c++}g.N(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.ki(e.element),g.qf(e);this.stills.length=c}};
g.h.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Rl())};
g.h.WS=function(){this.B+=this.stills.length;this.Rl()};
g.h.XS=function(){this.B-=this.stills.length;this.Rl()};
g.h.pN=function(){return this.j.Rh()};
g.h.BD=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.hn(),this.tb&&this.Rl()):(this.D=!0,this.tb&&B3(this)&&(2===a?this.j.Hu():3===a&&this.j.Yq()))};
g.h.VS=function(a){if(a){for(a=0;a<this.stills.length;a++)this.I.Za(this.stills[a].element,!0);this.BD(1)}else this.C=null,this.D=!1;this.Rl()};
g.h.Ae=function(){return this.tb&&B3(this)};g.v(D3,g.lL);g.h=D3.prototype;g.h.Br=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!AWa(this.player)||b;var c=a.xe||g.CC(a.B),d=this.player.Jw();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Ae=function(){return this.endScreen.Ae()};
g.h.AV=function(){return this.Ae()?this.endScreen.pN():!1};
g.h.qa=function(){this.player.jf("endscreen");g.lL.prototype.qa.call(this)};
g.h.load=function(){var a=this.player.getVideoData();var b=a.dO;if(b&&b.videoId){var c=this.player.sb().Nd.get("heartbeat");a&&a.suggestions&&a.suggestions.length&&b.videoId===a.suggestions[0].videoId&&!a.IK?a=!1:(this.player.rk(b.videoId,void 0,void 0,!0,!0,b),c&&c.hB("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0)}else a=!1;a||(g.lL.prototype.load.call(this),this.endScreen.show())};
g.h.unload=function(){g.lL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.onCueRangeEnter=function(a){this.Br()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.onVideoDataChange=function(){CWa(this);this.B&&BWa(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new w3(this.player):this.endScreen=new A3(this.player),g.H(this,this.endScreen),g.ZK(this.player,this.endScreen.element,4))};g.kL("endscreen",D3);})(_yt_player);
